# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=50)),
                ('module_relevant', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module_ed',
            fields=[
                ('module_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('module_start', models.DateTimeField()),
                ('module_stop', models.DateTimeField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradebook.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('study_short', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Studying',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradebook.Module_ed')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradebook.Student')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradebook.Study')),
            ],
        ),
    ]
