# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 10:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='study_long',
            field=models.CharField(default=datetime.datetime(2017, 9, 12, 10, 7, 42, 134018, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
