# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0002_study_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('teachers', models.ManyToManyField(to='gradebook.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Module_ed',
            fields=[
                ('module_ed_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('courses', models.ManyToManyField(to='gradebook.Course')),
            ],
        ),
    ]
