# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0004_criterion_studying_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradebook.Student')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradebook.Teacher')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradebook.Test')),
            ],
        ),
    ]
