# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 14:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0005_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advisor',
            old_name='advisor_id',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_id',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='module_ed',
            old_name='module_ed_id',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='_id',
        ),
        migrations.AddField(
            model_name='advisor',
            name='mail',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='studies',
            field=models.ManyToManyField(to='gradebook.Study'),
        ),
        migrations.AddField(
            model_name='module',
            name='start',
            field=models.DateField(default=datetime.date(1, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='stop',
            field=models.DateField(default=datetime.date(1, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='mail',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='full_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='job',
            field=models.CharField(choices=[('T', 'Teacher'), ('A', 'Teaching Assistant')], default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='mail',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
