"""
Django settings for Seth project.

Generated by 'django-admin startproject' using Django 1.11.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

OS_PATH = '/var/www/html/'

# SECURITY WARNING: keep the secret key used in production secret!
with open('{}secrets/django_secret'.format(OS_PATH)) as f:
    SECRET_KEY = f.read().strip()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['farm11.ewi.utwente.nl', 'localhost']

# Application definition

INSTALLED_APPS = [
    'Grades.apps.GradesConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dashboard',
    'module_management',
    'importer',
    'human_resource'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Seth.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'dashboard.context_processors.installed_apps.installed_apps',
            ],
        },
    },
]

WSGI_APPLICATION = 'Seth.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

with open('{}secrets/postgres_host'.format(OS_PATH)) as hfile:
    with open('{}secrets/postgres_password'.format(OS_PATH)) as pwfile:

        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql_psycopg2',
                'NAME': 'djangoseth',
                'USER': 'djangoseth',
                'PASSWORD': pwfile.read().strip(),
                'HOST': hfile.read().strip(),
            }
        }


# Add radius authentication.
with open('{}secrets/radius_host'.format(OS_PATH)) as radius_host:
    with open('{}secrets/radius_secret'.format(OS_PATH)) as radius_secret:
        AUTHENTICATION_BACKENDS = (
            'radiusauth.backends.RADIUSBackend',
            'django.contrib.auth.backends.ModelBackend',
        )

        RADIUS_SERVER = radius_host.read().strip()
        RADIUS_PORT = 1812
        RADIUS_SECRET = radius_secret.read().strip()


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    'static/Seth'
]

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'

LOGOUT_URL = '/logout/'
LOGOUT_REDIRECT_URL = '/successfully_logged_out/'

FIXTURE_DIRS = (
    './fixtures/',
)

# Console mailing backend for development
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Django-excel requires these, used in importer.
FILE_UPLOAD_HANDLERS = ("django_excel.ExcelMemoryFileUploadHandler",
                        "django_excel.TemporaryExcelFileUploadHandler")
