# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 12:10
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('employee_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('start', models.DateField(default=datetime.date(1, 1, 1))),
                ('stop', models.DateField(default=datetime.date(1, 1, 1))),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=32)),
                ('role', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(default=datetime.date(1, 1, 1))),
                ('description', models.CharField(max_length=256, null=True)),
                ('grade', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Module_ed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(default=datetime.date(1, 1, 1))),
                ('stop', models.DateField(default=datetime.date(1, 1, 1))),
                ('courses', models.ManyToManyField(to='Grades.Course')),
                ('module', models.ManyToManyField(to='Grades.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('short_name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=32, null=True)),
                ('modules', models.ManyToManyField(to='Grades.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Studying',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=32)),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grades.Module_ed')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grades.Student')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grades.Study')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=16, null=True)),
                ('job', models.CharField(choices=[('T', 'Teacher'), ('A', 'Teaching Assistant')], max_length=1)),
                ('student_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Grades.Student')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True)),
                ('_type', models.CharField(choices=[('E', 'Exam'), ('A', 'Assignment'), ('P', 'Project')], max_length=1)),
                ('time', models.DateField(default=datetime.date(1, 1, 1))),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grades.Course')),
            ],
        ),
        migrations.AddField(
            model_name='module_ed',
            name='module_coordinator',
            field=models.ManyToManyField(to='Grades.Teacher'),
        ),
        migrations.AddField(
            model_name='grade',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grades.Student'),
        ),
        migrations.AddField(
            model_name='grade',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grades.Teacher'),
        ),
        migrations.AddField(
            model_name='grade',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grades.Test'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='module_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grades.Module_ed'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grades.Study'),
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(to='Grades.Teacher'),
        ),
        migrations.AddField(
            model_name='advisor',
            name='studies',
            field=models.ManyToManyField(to='Grades.Study'),
        ),
        migrations.AddField(
            model_name='advisor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
