# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='released',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='course',
            name='code_extension',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='module_ed',
            name='module_code_extension',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='module_ed',
            name='year',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('T', 'Teacher'), ('S', 'Student'), ('A', 'Teaching Assistant'), ('V', 'Study Advisor')], max_length=1),
        ),
        migrations.AlterField(
            model_name='test',
            name='_type',
            field=models.CharField(choices=[('E', 'Exam'), ('A', 'Assignment'), ('P', 'Project')], max_length=1),
        ),
    ]
