# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='end',
            field=models.DateField(null=True),
        ),
    ]
