# Generated by Django 2.1.5 on 2019-02-02 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moduleedition',
            options={'ordering': ['-year', '-block', 'module']},
        ),
        migrations.AlterModelOptions(
            name='studying',
            options={'verbose_name': 'Enrollment', 'verbose_name_plural': 'Enrollments'},
        ),
        migrations.AlterField(
            model_name='grade',
            name='description',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studying',
            name='role',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='moduleedition',
            unique_together=set(),
        ),
    ]
