# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='studies',
        ),
        migrations.RemoveField(
            model_name='advisor',
            name='user',
        ),
        migrations.DeleteModel(
            name='Advisor',
        ),
    ]
