# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 12:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0002_auto_20170917_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='start',
            field=models.DateField(default=datetime.date(1, 1, 1)),
        ),
        migrations.AddField(
            model_name='module',
            name='stop',
            field=models.DateField(default=datetime.date(9999, 12, 31)),
        ),
        migrations.AlterField(
            model_name='module_ed',
            name='stop',
            field=models.DateField(default=datetime.date(9999, 12, 31)),
        ),
        migrations.AlterField(
            model_name='module_ed',
            name='year',
            field=models.DateField(default=datetime.date(2017, 9, 18)),
        ),
    ]
