# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0002_auto_20170925_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module_coordinator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mc_assistant', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='module_ed',
            name='module_coordinator',
        ),
        migrations.RemoveField(
            model_name='person',
            name='studies',
        ),
        migrations.AddField(
            model_name='study',
            name='advisors',
            field=models.ManyToManyField(to='Grades.Person'),
        ),
        migrations.AddField(
            model_name='module_coordinator',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grades.Module_ed'),
        ),
        migrations.AddField(
            model_name='module_coordinator',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grades.Person'),
        ),
        migrations.AddField(
            model_name='module_ed',
            name='coordinator',
            field=models.ManyToManyField(through='Grades.Module_coordinator', to='Grades.Person'),
        ),
    ]
