# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 12:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0003_auto_20170918_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='maximum_grade',
            field=models.DecimalField(decimal_places=3, default=10.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='grade',
            name='minimum_grade',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='grade',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='test',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
    ]
