# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0003_auto_20171004_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinator',
            old_name='module',
            new_name='module_edition',
        ),
    ]
