# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0004_auto_20170918_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='maximum_grade',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='minimum_grade',
        ),
        migrations.AddField(
            model_name='test',
            name='maximum_grade',
            field=models.DecimalField(decimal_places=3, default=10.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='test',
            name='minimum_grade',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=6),
        ),
    ]
