# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0005_auto_20171005_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordinator',
            options={'ordering': ['person']},
        ),
        migrations.AlterModelOptions(
            name='moduleedition',
            options={'ordering': ['module', '-year', '-block']},
        ),
        migrations.AlterModelOptions(
            name='modulepart',
            options={'ordering': ['module_edition', 'name']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['university_number']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['person']},
        ),
        migrations.AddField(
            model_name='person',
            name='Student e-mail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='moduleedition',
            name='block',
            field=models.CharField(choices=[('1A', 'Block 1A'), ('1B', 'Block 1B'), ('2A', 'Block 2A'), ('2B', 'Block 2B'), ('3A', 'Block 3A'), ('3B', 'Block 3B'), ('JAAR', 'Block JAAR')], max_length=16),
        ),
    ]
