# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 14:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0006_auto_20170913_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='module_ed',
            name='module_coordinator',
            field=models.ManyToManyField(to='Grades.Teacher'),
        ),
        migrations.AddField(
            model_name='module_ed',
            name='start',
            field=models.DateField(default=datetime.date(1, 1, 1)),
        ),
        migrations.AddField(
            model_name='module_ed',
            name='stop',
            field=models.DateField(default=datetime.date(1, 1, 1)),
        ),
    ]
