# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0006_auto_20171006_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Student e-mail',
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Student e-mail'),
        ),
    ]
