# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 15:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0007_auto_20170913_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='start',
            field=models.DateField(default=datetime.date(1, 1, 1)),
        ),
        migrations.AddField(
            model_name='advisor',
            name='stop',
            field=models.DateField(default=datetime.date(1, 1, 1)),
        ),
        migrations.AddField(
            model_name='grade',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='time',
            field=models.DateField(default=datetime.date(1, 1, 1)),
        ),
        migrations.AddField(
            model_name='test',
            name='_type',
            field=models.CharField(choices=[('E', 'Exam'), ('A', 'Assignment'), ('P', 'Project')], default='E', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='time',
            field=models.DateField(default=datetime.date(1, 1, 1)),
        ),
    ]
