# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0007_auto_20171006_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='end',
        ),
        migrations.RemoveField(
            model_name='module',
            name='start',
        ),
        migrations.RemoveField(
            model_name='moduleedition',
            name='end',
        ),
        migrations.RemoveField(
            model_name='moduleedition',
            name='start',
        ),
        migrations.RemoveField(
            model_name='person',
            name='end',
        ),
        migrations.RemoveField(
            model_name='person',
            name='start',
        ),
        migrations.RemoveField(
            model_name='test',
            name='time',
        ),
    ]
